import '@/styles/globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({children}) => {
  return (
    <html lang ="en">
        <body>
            <main className=''>
                {children}
            </main>
        </body>
    </html>
  )
}

export default RootLayout